(() => {
'use strict';
const $=id=>document.getElementById(id);
const S={config:null,sessionId:null,session:null,scene:null,plate:null,cloth:null,mesh:null,refined:null,pendingRefined:null,workflow:null,nodes:[],drag:null,raf:null,refineTimer:null};
const api=async(url,opt={})=>{const r=await fetch(url,opt);let d;try{d=await r.json()}catch{d={ok:false,error:await r.text()}}if(!r.ok||d.ok===false)throw new Error(d.error||`HTTP ${r.status}`);return d};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const status=(t,k='')=>{const e=$('statusPill');e.textContent=t;e.className=`pill ${k}`};
const fail=e=>{console.error(e);status(e.message||String(e),'error')};
const opts=(el,rows,empty='None')=>{const old=el.value;el.innerHTML=`<option value="">${esc(empty)}</option>`+(rows||[]).map(x=>`<option value="${esc(x.name||x)}">${esc(x.name||x)}</option>`).join('');if([...el.options].some(o=>o.value===old))el.value=old};
function setTab(n){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===n));document.querySelectorAll('.tab-pane').forEach(x=>x.classList.toggle('active',x.id===`tab-${n}`))}
function genHTML(stage){const m=S.config.models||{},os=a=>'<option value=""></option>'+(a||[]).map(x=>`<option>${esc(x)}</option>`).join('');return `<div class="gen-settings" data-generation="${stage}"><div class="title">Generation settings</div><div class="two-col"><label>Steps<input data-key="steps" type="number" value="4"></label><label>CFG<input data-key="cfg" type="number" step=".05" value="1"></label><label>Sampler<select data-key="sampler">${os(m.samplers)}</select></label><label>Scheduler<select data-key="scheduler">${os(m.schedulers)}</select></label><label>Seed<input data-key="seed" type="number" value="42"></label><label>Denoise<input data-key="denoise" type="number" step=".01" value="1"></label></div><label>Checkpoint<select data-key="checkpoint">${os(m.checkpoints)}</select></label><label>Diffusion model<select data-key="diffusion_model">${os(m.diffusion_models)}</select></label><label>VAE<select data-key="vae">${os(m.vae)}</select></label><label>Text encoder<select data-key="text_encoder">${os(m.text_encoders)}</select></label><details><summary>LoRA slots</summary>${[1,2,3,4].map(i=>`<div class="lora-row"><label>LoRA ${i}<select data-lora="${i}" data-key="name">${os(m.loras)}</select></label><label>Model<input data-lora="${i}" data-key="strength_model" type="number" step=".05" value="1"></label><label>CLIP<input data-lora="${i}" data-key="strength_clip" type="number" step=".05" value="1"></label></div>`).join('')}</details></div>`}
function readGen(stage){const r=document.querySelector(`[data-generation="${stage}"]`),o={};if(!r)return o;r.querySelectorAll('[data-key]:not([data-lora])').forEach(e=>{let v=e.value;if(['steps','seed'].includes(e.dataset.key))v=parseInt(v||0);if(['cfg','denoise'].includes(e.dataset.key))v=parseFloat(v||0);o[e.dataset.key]=v});o.loras=[];for(let i=1;i<=4;i++){let n=r.querySelector(`[data-lora="${i}"][data-key="name"]`)?.value;if(n)o.loras.push({name:n,strength_model:+r.querySelector(`[data-lora="${i}"][data-key="strength_model"]`).value,strength_clip:+r.querySelector(`[data-lora="${i}"][data-key="strength_clip"]`).value})}return o}
async function config(){S.config=await api('/bird-cage/api/config');$('detectorPrompt').value=S.config.defaults.detector_prompt;$('revealPrompt').value=S.config.defaults.reveal_prompt;$('cleanupPrompt').value=S.config.defaults.cleanup_prompt;$('refinePrompt').value=S.config.defaults.refine_prompt;$('revealGeneration').innerHTML=genHTML('reveal');$('cleanupGeneration').innerHTML=genHTML('cleanup');$('refineGeneration').innerHTML=genHTML('refine');profiles()}
function profiles(){const p=S.config.profiles||{};opts($('segmentProfile'),p.segment,'Manual/uploaded mask');opts($('revealProfile'),p.reveal,'Uploaded revealed image');opts($('cleanupProfile'),p.cleanup,'No cleanup');opts($('refineProfile'),p.refine,'Choose refine workflow');$('profileList').innerHTML=Object.entries(p).flatMap(([stage,rows])=>rows.map(x=>`<div class="profile-card"><div><span class="stage">${esc(stage)}</span><br><b>${esc(x.name)}</b></div><button data-del="${esc(stage)}/${esc(x.name)}">Delete</button></div>`)).join('');document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{const [s,n]=b.dataset.del.split('/');await api(`/bird-cage/api/workflows/${encodeURIComponent(s)}/${encodeURIComponent(n)}`,{method:'DELETE'});S.config.profiles=(await api('/bird-cage/api/workflows')).profiles;profiles()})}
async function sessions(prefer){const d=await api('/bird-cage/api/sessions'),e=$('sessionSelect');e.innerHTML='<option value="">No session</option>'+d.sessions.map(x=>`<option value="${esc(x.id)}">${esc(x.name||x.id)} · ${esc(x.status||'')}</option>`).join('');let id=prefer||S.sessionId||d.sessions[0]?.id;if(id){e.value=id;await load(id)}}
async function makeSession(){let name=prompt('Scene name','bird-cage')||'bird-cage',d=await api('/bird-cage/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});S.sessionId=d.session.id;await sessions(S.sessionId)}
async function load(id){if(!id)return;const d=await api(`/bird-cage/api/session/${encodeURIComponent(id)}`);S.sessionId=id;S.session=d.session;S.scene=d.scene;$('sceneTitle').textContent=d.session.name||id;$('sceneMeta').textContent=` · ${d.session.status||''}`;status(d.session.status||'ready','ok');if(d.scene?.asset_urls?.plate&&d.scene?.asset_urls?.cloth)await loadScene(d.scene);else clearCanvas()}
async function upload(role,file){if(!file)return;if(!S.sessionId)await makeSession();const f=new FormData();f.append('role',role);f.append('file',file);status(`Uploading ${role}…`);await api(`/bird-cage/api/session/${encodeURIComponent(S.sessionId)}/upload`,{method:'POST',body:f});await load(S.sessionId)}
const img=url=>new Promise((ok,no)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=no;i.src=url+'?t='+Date.now()});
function clearCanvas(){S.plate=S.cloth=S.mesh=S.refined=S.pendingRefined=null;$('emptyState').classList.remove('hidden');let c=$('sceneCanvas');c.getContext('2d').clearRect(0,0,c.width,c.height)}
async function loadScene(scene){S.scene=scene;S.plate=await img(scene.asset_urls.plate);S.cloth=await img(scene.asset_urls.cloth);S.refined=S.pendingRefined=null;let c=$('sceneCanvas');c.width=scene.width;c.height=scene.height;$('emptyState').classList.add('hidden');resetMesh();loop()}
function resetMesh(){if(!S.scene||!S.cloth)return;const b=S.scene.cloth_bbox,cols=S.scene.mesh?.cols||16,rows=S.scene.mesh?.rows||16,pts=[];for(let y=0;y<=rows;y++)for(let x=0;x<=cols;x++)pts.push({x:b.x+b.width*x/cols,y:b.y+b.height*y/rows,px:b.x+b.width*x/cols,py:b.y+b.height*y/rows,u:S.cloth.width*x/cols,v:S.cloth.height*y/rows});S.mesh={b,cols,rows,pts};S.refined=S.pendingRefined=null}
function idx(x,y){return y*(S.mesh.cols+1)+x}
function physics(){if(!S.mesh)return;const m=S.mesh,d=.985;for(const p of m.pts){if(p.grab)continue;let vx=(p.x-p.px)*d,vy=(p.y-p.py)*d;p.px=p.x;p.py=p.y;p.x+=vx;p.y+=vy+.04}for(let it=0;it<5;it++){for(let y=0;y<=m.rows;y++)for(let x=0;x<=m.cols;x++){let a=m.pts[idx(x,y)];if(x<m.cols)constraint(a,m.pts[idx(x+1,y)],m.b.width/m.cols);if(y<m.rows)constraint(a,m.pts[idx(x,y+1)],m.b.height/m.rows)}}}
function constraint(a,b,len){let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,q=(d-len)/d*.5;if(!a.grab){a.x+=dx*q;a.y+=dy*q}if(!b.grab){b.x-=dx*q;b.y-=dy*q}}
function tri(ctx,im,a,b,c){ctx.save();ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(c.x,c.y);ctx.closePath();ctx.clip();const den=a.u*(b.v-c.v)+b.u*(c.v-a.v)+c.u*(a.v-b.v);if(Math.abs(den)<1e-6){ctx.restore();return}const A=(a.x*(b.v-c.v)+b.x*(c.v-a.v)+c.x*(a.v-b.v))/den,B=(a.y*(b.v-c.v)+b.y*(c.v-a.v)+c.y*(a.v-b.v))/den,C=(a.x*(c.u-b.u)+b.x*(a.u-c.u)+c.x*(b.u-a.u))/den,D=(a.y*(c.u-b.u)+b.y*(a.u-c.u)+c.y*(b.u-a.u))/den,E=(a.x*(b.u*c.v-c.u*b.v)+b.x*(c.u*a.v-a.u*c.v)+c.x*(a.u*b.v-b.u*a.v))/den,F=(a.y*(b.u*c.v-c.u*b.v)+b.y*(c.u*a.v-a.u*c.v)+c.y*(a.u*b.v-b.u*a.v))/den;ctx.setTransform(A,B,C,D,E,F);ctx.drawImage(im,0,0);ctx.restore()}
function render(target=$('sceneCanvas')){let c=target,x=c.getContext('2d');x.setTransform(1,0,0,1,0,0);x.clearRect(0,0,c.width,c.height);if(S.refined){x.drawImage(S.refined,0,0,c.width,c.height);return}if(!S.plate)return;x.drawImage(S.plate,0,0,c.width,c.height);if(!S.mesh)return;let m=S.mesh;for(let y=0;y<m.rows;y++)for(let z=0;z<m.cols;z++){let a=m.pts[idx(z,y)],b=m.pts[idx(z+1,y)],d=m.pts[idx(z,y+1)],e=m.pts[idx(z+1,y+1)];tri(x,S.cloth,a,b,e);tri(x,S.cloth,a,e,d)}}
function loop(){if(S.raf)return;const tick=()=>{S.raf=requestAnimationFrame(tick);if(S.mesh&&!S.refined){physics();render()}};tick()}
function pos(ev){let c=$('sceneCanvas'),r=c.getBoundingClientRect();return{x:(ev.clientX-r.left)*c.width/r.width,y:(ev.clientY-r.top)*c.height/r.height}}
function pointerDown(ev){if(!S.mesh)return;S.refined=S.pendingRefined=null;let q=pos(ev),best=null,dist=Infinity;for(const p of S.mesh.pts){let d=Math.hypot(p.x-q.x,p.y-q.y);if(d<dist){best=p;dist=d}}if(best&&dist<Math.max(S.mesh.b.width,S.mesh.b.height)*.35){best.grab=true;S.drag=best;$('sceneCanvas').setPointerCapture(ev.pointerId);$('sceneCanvas').classList.add('dragging');clearTimeout(S.refineTimer)}}
function pointerMove(ev){if(S.drag){let q=pos(ev);S.drag.x=q.x;S.drag.y=q.y;S.drag.px=q.x;S.drag.py=q.y}}
function pointerUp(){if(!S.drag)return;S.drag.grab=false;S.drag=null;$('sceneCanvas').classList.remove('dragging');scheduleRefine()}
function changedMask(){let c=document.createElement('canvas');c.width=S.scene.width;c.height=S.scene.height;let x=c.getContext('2d');x.fillStyle='black';x.fillRect(0,0,c.width,c.height);x.fillStyle='white';let b=S.mesh.b;x.fillRect(b.x-20,b.y-20,b.width+40,b.height+40);let xs=S.mesh.pts.map(p=>p.x),ys=S.mesh.pts.map(p=>p.y),l=Math.min(...xs)-30,t=Math.min(...ys)-30,r=Math.max(...xs)+30,bt=Math.max(...ys)+30;x.fillRect(l,t,r-l,bt-t);return c.toDataURL('image/png')}
async function refine(){if(!S.sessionId||!S.mesh||!$('refineProfile').value)return;try{status('Refining…');$('refineState').textContent='AI refine running…';let tmp=document.createElement('canvas');tmp.width=S.scene.width;tmp.height=S.scene.height;render(tmp);let body={profile:$('refineProfile').value,composite_data_url:tmp.toDataURL('image/png'),mask_data_url:changedMask(),prompt:$('refinePrompt').value,negative_prompt:$('refineNegative').value,settings:readGen('refine')};let d=await api(`/bird-cage/api/session/${encodeURIComponent(S.sessionId)}/refine`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});S.pendingRefined=await img(d.asset_url);S.refined=S.pendingRefined;render();$('refineState').textContent='Refine preview · Accept or Reject';status('Refine ready','ok')}catch(e){fail(e);$('refineState').textContent=''}}
function scheduleRefine(){if(!$('refineEnabled').checked)return;clearTimeout(S.refineTimer);S.refineTimer=setTimeout(refine,+$('refineDebounce').value||450)}
function initMask(){let c=$('maskCanvas'),drawing=false;const source=()=>S.sessionId?`/bird-cage/api/session/${encodeURIComponent(S.sessionId)}/asset/source.png?t=${Date.now()}`:null;let i=new Image;i.onload=()=>{c.width=i.width;c.height=i.height;c.getContext('2d').clearRect(0,0,c.width,c.height)};if(source())i.src=source();const p=e=>{let r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};const draw=e=>{if(!drawing)return;let q=p(e),x=c.getContext('2d');x.globalCompositeOperation=$('eraseMask').checked?'destination-out':'source-over';x.fillStyle='white';x.beginPath();x.arc(q.x,q.y,+$('brushSize').value/2,0,Math.PI*2);x.fill()};c.onpointerdown=e=>{drawing=true;c.setPointerCapture(e.pointerId);draw(e)};c.onpointermove=draw;c.onpointerup=()=>drawing=false;$('clearMaskBtn').onclick=()=>c.getContext('2d').clearRect(0,0,c.width,c.height);$('saveMaskBtn').onclick=async()=>{await api(`/bird-cage/api/session/${encodeURIComponent(S.sessionId)}/manual-mask`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data_url:c.toDataURL('image/png')})});$('maskEditor').classList.add('hidden');status('Mask saved','ok')}}
async function compile(){if(!S.sessionId)return fail(new Error('Create a scene first'));let body={segment_profile:$('segmentProfile').value||null,reveal_profile:$('revealProfile').value||null,cleanup_profile:$('cleanupProfile').value||null,detector_prompt:$('detectorPrompt').value,reveal_prompt:$('revealPrompt').value,negative_prompt:$('negativePrompt').value,cleanup_prompt:$('cleanupPrompt').value,box_threshold:+$('boxThreshold').value,text_threshold:+$('textThreshold').value,mask_expand:+$('maskExpand').value,mask_feather:+$('maskFeather').value,invert_mask:$('invertMask').checked,refine_enabled:$('refineEnabled').checked,refine_debounce_ms:+$('refineDebounce').value,reveal:readGen('reveal'),cleanup:readGen('cleanup')};try{$('compileBtn').disabled=true;status('Compiling…');await api(`/bird-cage/api/session/${encodeURIComponent(S.sessionId)}/compile`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await load(S.sessionId);status('Scene ready','ok')}catch(e){fail(e)}finally{$('compileBtn').disabled=false}}
async function workflowFile(file){try{S.workflow=JSON.parse(await file.text());let d=await api('/bird-cage/api/workflows/inspect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workflow:S.workflow})});S.nodes=d.nodes;let output=$('workflowOutputNode');output.innerHTML='<option value="">Auto detect</option>'+S.nodes.map(n=>`<option value="${esc(n.id)}">${esc(n.id)} · ${esc(n.title)}</option>`).join('');let candidates=S.nodes.flatMap(n=>n.inputs.filter(i=>i.bindable).map(i=>({v:`${n.id}|${i.name}`,t:`${n.id} · ${n.title} · ${i.name}`})));$('bindingEditor').classList.remove('empty');$('bindingEditor').innerHTML=S.config.semantic_fields.map(k=>`<div class="binding-row"><code>${esc(k)}</code><select data-bind="${esc(k)}"><option value="">—</option>${candidates.map(c=>`<option value="${esc(c.v)}">${esc(c.t)}</option>`).join('')}</select></div>`).join('');$('saveWorkflowBtn').disabled=false}catch(e){fail(e)}}
async function saveWorkflow(){let bindings={};document.querySelectorAll('[data-bind]').forEach(e=>{if(e.value){let [node,input]=e.value.split('|');bindings[e.dataset.bind]=[{node,input}]}});let body={stage:$('workflowStage').value,name:$('workflowName').value,description:$('workflowDescription').value,output_node:$('workflowOutputNode').value||null,workflow:S.workflow,bindings};let d=await api('/bird-cage/api/workflows',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});S.config.profiles=d.profiles;profiles();status('Workflow saved','ok')}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('newSessionBtn').onclick=makeSession;$('sessionSelect').onchange=e=>load(e.target.value);$('sourceFile').onchange=e=>upload('source',e.target.files[0]);$('revealedFile').onchange=e=>upload('revealed',e.target.files[0]);$('maskFile').onchange=e=>upload('manual_mask',e.target.files[0]);$('compileBtn').onclick=compile;$('resetClothBtn').onclick=resetMesh;$('refineNowBtn').onclick=refine;$('acceptRefineBtn').onclick=()=>{if(S.pendingRefined){S.refined=S.pendingRefined;$('refineState').textContent='Refine accepted'}};$('rejectRefineBtn').onclick=()=>{S.refined=S.pendingRefined=null;render();$('refineState').textContent='Refine rejected'};$('openMaskEditorBtn').onclick=()=>{$('maskEditor').classList.remove('hidden');initMask()};$('closeMaskEditorBtn').onclick=()=>$('maskEditor').classList.add('hidden');$('workflowFile').onchange=e=>workflowFile(e.target.files[0]);$('saveWorkflowBtn').onclick=saveWorkflow;let c=$('sceneCanvas');c.onpointerdown=pointerDown;c.onpointermove=pointerMove;c.onpointerup=pointerUp;c.onpointercancel=pointerUp}
(async()=>{try{bind();await config();await sessions();status('Ready','ok')}catch(e){fail(e)}})();
})();
